# 예외

- 예외를 처리하기 위해 사용하는 방법



## try... catch.. finally

- 예외에서 핵심적인 역할을 담당하는 문법적 요소

```java
try{
  예외의 발생이 예상되는 로직
} catch(예외 클래스 인스턴스){
  예외가 발생되었을때 실행되는 로직
} finally{
  // finally는 optional
  예외 여부와 관계없이 실행되는 로직
}
```

- try 안에는 예외 상황이 발생할 것으로 예상되는 로직 위치시킴
- catch 안에는 예외가 발생했을 때 뒷수습을 하기위한 로직이 위치 
  - 다중 catch문 사용 가능
  - catch 구문의 뒤에 있는 예외일수록 포괄적인 것이다.

```java
// e는 변수
// Exception은 변수의 데이터 타입 의미 (자바에서 기본적으로 제공하는 클래스)
} catch(Exception e){
  
}
```



## 뒷수습 방법

- `Exception e` 로 예외를 처리할 경우 기본 메소드
  - `e.getMessage()` 
    - 오류에 대한 기본적인 내용 출력
  - `e.toString()`
    - `e.getMessage()` 보다 더 자세한 예외 정보 제공
  - `e.printStackTrace()`
    - 리턴 값이 따로 없음
    - 메소드가 내부적으로 예외 결과를 화면에 출력
    - 가장 자세한 예외 정보를 제공



## throw와 throws

- throw 현재 메소드 내에서 예외를 강제로 발생시키거나 현재 메소드에게 exception 정보를 전달
    ```java
    public void divide(){
      if(this.right == 0){
        // DivideException 이라는 예외를 던짐
        // DivideException은 사용자가 정의한 예외
        throw new DivideException("0으로 나누는 것은 허용되지 않습니다.");
      }
      System.out.print(this.left/this.right);
    }
    ```

  - 메소드를 발생시켜 메서드 내에서 예외 처리

  - throw 뒤에는 예외 정보를 가지고 있는 예외 클래스가 위치 함
    - 뒤에 위치하는 예외 클래스를 기준으로 예외 상황의 원인에 대한 정보를 알 수 있음
    - `throw 예외 클래스`
    - `throw new ArithmeticException`

- throws는 예외처리를 상위 사용자에게 넘기는 것

  - 현재 메서드에서 자신을 호출한 상위 메소드로 Exception을 발생시킴

- 자바는 예외를 모두 같은 방식으로 다루지 않음

  - 예를 들면, `IOException` 과 `ArithmeticException` 은 서로 다른 방식으로 예외를 다룸

    - `IOException` 은 예외를 강제하지만 `ArithmeticException` 은 예외를 강제하지 않음
    - `ArhtimeticException`은 상위 클래스에 `RuntimeException` 이 존재한다. 그렇기때문에 `unchecked` 예외이고, 그렇다면 반드시 `try...catch` 나 `throws` 를 사용해서 체크를 안해도 되기 때문이다.

  - `IOException` 은 함수내에 `throw IOException` 만을 적을 수 없다. 

    함수 뒤에 `throws IOException` 을 적거나 `try ... catch` 구문을 이용해야 한다.

    ```java
    package ExceptionTest;
    
    import java.io.IOException;
    
    public class E {
        void throwArithmeticException(){
            throw new ArithmeticException();
        }
        
        // IOException 의 경우 함수 뒤에 throws 키워드를 붙이거나 
        void throwIOException() throws IOException{
    
        }
        
        // try ... catch 구문을 이용해야 함
        void throwIOException2(){
            try{
                throw new IOException();
            }catch(Exception e){
    
            }
        }
    }
    ```



## Throwable

![예외종류](https://s3.ap-northeast-2.amazonaws.com/opentutorials-user-file/module/516/2099.png)



- `Throwable` : 모든 예외들이 공통적으로 가지고 있는 조상. 직접 사용하지는 않음

- `Error` : 이 에러는 애플리케이션을 구동하는 가상머신에 문제가 생겼을때 발생하는 예외

- `Exception` 

  - `checked` : `RuntimeException` 제외한 `Exception`의 하위 클래스
    - `IOException` 같은 것
  - `unchecked` : `RuntimeException` 의 하위 클래스

  - `checked` 는 반드시 예외 처리를 해야함. 그렇기 때문에 `try...catch` 구문이나 `throws 예외` 를 반드시 해주어야함. `unchecked` 는 그럴 필요 없음.



## 예외 만들기

- 표준 예외 클래스 이외에 필요한 경우 예외를 직접 만들 수 있음
- 예외를 만들때는 `checked` 를 할 것인지, `unchecked` 를 할 것인지 결정해야 함
- checked 사용하는 경우 : API 쪽에서 예외를 던졌을 때, API 사용자 쪽에서 예외 상황을 복구 할 수 있을 때
  - 사용자에게 문제를 해결할 기회를 주는 것
  - 남용할 경우, API 사용자를 힘들게 할 수 있음
- Unchecked 사용하는 경우 : 사용자가 API 사용방법을 어겨서 발생하는 문제거나 예외상황이 이미 발생한 시점에서 그냥 프로그램을 종료하는것이 더 안전할때

- unckecked 예외 예시

  ```java
  package ExceptionTest;
  // 예외 생성 예시
  // 나중에 에외를 부를때는 
  // `new DivideException` 이라는 클래스 이름으로 부름
  class DivideException extends RuntimeException{
      // 생성자
      DivideException(){
          super();
      }
      DivideException(String message){
          super(message);
      }
  }
  
  class Calculator{
      int left, right;
      public void setOperand(int left, int right){
          this.left = left;
          this.right = right;
      }
  
      public void divide(){
          if(this.right == 0){
              throw new DivideException("0으로 나누면 안돼요!");
          }
          System.out.println(this.left / this.right);
      }
  }
  
  public class CalculatorDemo {
      public static void main(String[] args) {
          Calculator c1 = new Calculator();
          c1.setOperand(10, 0);
          c1.divide();
      }
  }
  //Exception in thread "main" ExceptionTest.DivideException: 0으로 나누면 안돼요!
  //	at ExceptionTest.Calculator.divide(CalculatorDemo.java:22)
  //	at ExceptionTest.CalculatorDemo.main(CalculatorDemo.java:32)
  ```

- checked 예시

  ```java
  // 이런식으로 throws 를 이용해서 예외를 던지거나 
  public void divide() throws DivideException{
    if(this.right == 0){
      throw new DivideException("0으로 나누면 안돼요!");
    }
    System.out.println(this.left / this.right);
  }
  // 이런식으로 try ... catch 구문 사용
  public void divide() {
    if(this.right == 0){
      try{
        throw new DivideException("0으로 나누면 안돼요!");
      }catch(DivideException e){
        e.printStackTrace();
      }
    }
    System.out.println(this.left / this.right);
  }
  ```

  

## 출처

> https://opentutorials.org/module/516/6226
>
> https://opentutorials.org/module/516/6227
>
> https://opentutorials.org/module/516/6228